services:
  BayDay\CoinCurrencyBundle\Templating\Helper\CurrencyHelper:
    decorates: sylius.templating.helper.currency
    arguments:
      $decoratedHelper: '@BayDay\CoinCurrencyBundle\Templating\Helper\CurrencyHelper.inner'
      $coinCurrencyCode: "%bayday.coin_currency.currency.code%"

  BayDay\CoinCurrencyBundle\Converter\CurrencyNameConverter:
    decorates: sylius.currency_name_converter
    arguments:
      $decoratedConverter: '@BayDay\CoinCurrencyBundle\Converter\CurrencyNameConverter.inner'
      $translator: "@translator"
      $coinCurrencyCode: "%bayday.coin_currency.currency.code%"

  BayDay\CoinCurrencyBundle\Form\Type\CurrencyType:
    decorates: sylius.form.type.currency
    arguments:
      $decoratedForm:  '@BayDay\CoinCurrencyBundle\Form\Type\CurrencyType.inner'
      $translator: "@translator"
      $coinCurrencyCode: "%bayday.coin_currency.currency.code%"
    tags:
      - {name: form.type, lazy: true}

  BayDay\CoinCurrencyBundle\Form\Type\CoinGatewayConfigurationType:
    tags:
      - {name: form.type, lazy: true}
      - {name: sylius.gateway_configuration_type, type: "%bayday.coin_currency.gateway%", label: bayday.coin_currency.payum_gateway.coin_checkout }

  BayDay\CoinCurrencyBundle\Payum\Action\CapturePaymentAction:
    decorates: sylius.payum_action.capture_payment
    arguments:
      $decoratedAction: '@BayDay\CoinCurrencyBundle\Payum\Action\CapturePaymentAction.inner'

  BayDay\CoinCurrencyBundle\Payum\Action\CaptureAction:
    public: true
    arguments:
      $customerRepository: '@sylius.repository.customer'
    tags:
      - { name: payum.action, factory: "%bayday.coin_currency.gateway%", gateway: "%bayday.coin_currency.gateway%" }

  BayDay\CoinCurrencyBundle\Validator\WalletFulfilledValidator:
    tags:
    - {name: validator.constraint_validator, lazy: true}

  BayDay\CoinCurrencyBundle\Validator\CoinCurrencyValidator:
    arguments:
      $coinCurrencyCode: "%bayday.coin_currency.currency.code%"
    tags:
      - {name: validator.constraint_validator, lazy: true}

  BayDay\CoinCurrencyBundle\EventListener\CurrencyListener:
    arguments:
      $translator: "@translator"
      $coinCurrencyCode: "%bayday.coin_currency.currency.code%"
    tags:
      - {name: doctrine.event_subscriber, lazy: true}

  BayDay\CoinCurrencyBundle\Builder\GatewayFactoryBuilder:
    arguments:
      $gatewayFactoryClass: BayDay\CoinCurrencyBundle\Payum\CoinPayumGatewayFactory
    tags:
      - {name: payum.gateway_factory_builder, factory: "%bayday.coin_currency.gateway%", lazy: true }

  BayDay\CoinCurrencyBundle\Operator\UserWalletOperator:
    public: true
    arguments:
      $customerManager: '@sylius.manager.customer'
      $stateMachineFactory: "@sm.factory"
      $coinProductCode: "%bayday.coin_currency.product.code%"

