BayDay\CoinCurrencyBundle\Model\Customer:
  properties:
    wallet:
      - GreaterThanOrEqual:
          value: 0
          message: "bayday.coin_currency.greater_than_zero"

Sylius\Component\Core\Model\Order:
  properties:
    currencyCode:
      - BayDay\CoinCurrencyBundle\Validator\CoinCurrency:
          groups: ["%bayday.coin_currency.validation_group%"]
