BayDay\CoinCurrencyBundle\Entity\ShopUser:
  properties:
    wallet:
      - GreaterThanOrEqual:
          value: 0
          message: "bayday.coin_currency.greater_than_zero"

#Sylius\Component\Core\Model\Payment:
#  constraints:
#    - BayDay\CoinCurrencyBundle\Validator\WalletFulfilled:
#        groups: ["BayDayCurrencyCoin"]


Sylius\Component\Core\Model\Order:
  properties:
    currencyCode:
      - BayDay\CoinCurrencyBundle\Validator\CoinCurrency:
          groups: ["%bayday.coin_currency.validation_group%"]